### PR TITLE
Add fast Python linter

### PR DESCRIPTION
**Pull request by anurlybayev**
Recently I saw someone post a link to [ruff](https://beta.ruff.rs/docs/) - Fast Python Linter. So I ran it against this code base and saw bunch of warnings. Some of which have been automatically fixed by `ruff`, but there remains another 21 that would need to be addressed, see below:
```zsh
poetry run ruff check --ignore E501  .     
examples/densenet/densenet.py:53:9: F811 Redefinition of unused `forward` from line 48
skyline/analysis/request_manager.py:137:9: E722 Do not use bare `except`
skyline/analysis/request_manager.py:166:9: E722 Do not use bare `except`
skyline/analysis/request_manager.py:174:9: E722 Do not use bare `except`
skyline/analysis/request_manager.py:182:9: E722 Do not use bare `except`
skyline/analysis/request_manager.py:190:9: E722 Do not use bare `except`
skyline/analysis/request_manager.py:198:9: E722 Do not use bare `except`
skyline/energy/measurer.py:27:31: E701 Multiple statements on one line (colon)
skyline/energy/measurer.py:50:32: E701 Multiple statements on one line (colon)
skyline/io/connection.py:94:9: E722 Do not use bare `except`
skyline/io/connection_acceptor.py:80:9: E722 Do not use bare `except`
skyline/profiler/iteration.py:222:25: E701 Multiple statements on one line (colon)
skyline/protocol/message_handler.py:153:9: E722 Do not use bare `except`
skyline/tracking/memory/activations.py:182:47: F821 Undefined name `tensor_iterable`
test/test_driver.py:3:1: F403 `from utils import *` used; unable to detect undefined names
test/test_driver.py:6:14: F405 `json` may be undefined, or defined from star imports: `utils`
test/test_driver.py:15:15: F405 `BackendContext` may be undefined, or defined from star imports: `utils`
test/test_driver.py:18:12: F405 `SkylineSession` may be undefined, or defined from star imports: `utils`
test/test_driver.py:19:29: E701 Multiple statements on one line (colon)
test/test_driver.py:23:42: E701 Multiple statements on one line (colon)
test/utils.py:11:27: E701 Multiple statements on one line (colon)
Found 21 errors.

```

Also, I've added [CodeClimate Quality](https://codeclimate.com/quality) integration to help us improve the codebase over time. Let's see how it looks on PRs.

### CODE REVIEW

**Review by michaelshin — APPROVED** [review]
Should we add pre-commit hooks to ensure our commits are linted as well?

**Comment by anurlybayev** [comment]
@michaelshin I think it is a good idea, given how fast `ruff` is.

**Comment by anurlybayev** [comment]
By the way, do you see the detailed code climate suggestions?

**Comment by michaelshin** [comment]
> By the way, do you see the detailed code climate suggestions?

I can see it once I click the link. Looks like it's all related to the examples. Can we ignore certain directories in Code Climate?

**Pull request closed without merging**
