### PR TITLE
chore: version bump for python and other dependencies

### PR DESCRIPTION
**Pull request by c-fteixeira**

### CODE REVIEW

**Comment by johncalesp** [comment]
I think python requirements is ^3.7 because of pytorch:
https://pytorch.org/get-started/locally/#linux-prerequisites-2
Python
Python 3.8-3.11 is generally installed by default on any of our supported Linux distributions, which meets our recommendation.

**Comment by c-fteixeira** [comment]
> I think python requirements is ^3.7 because of pytorch: https://pytorch.org/get-started/locally/#linux-prerequisites-2 Python Python 3.8-3.11 is generally installed by default on any of our supported Linux distributions, which meets our recommendation.

We could go to 3.8.. but it will EOL in 4 months, i was just trying to get ahead of it. 
from the link, that should be `^3.8` at least..

**Comment by johncalesp** [comment]
@jimgao1 let me us know, what you think

**Review by johncalesp — APPROVED** [review]
LGTM!

**Pull request merged**
